# Generated by Django 3.2 on 2022-10-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nip', models.CharField(max_length=10, unique=True)),
                ('krs', models.CharField(max_length=10, unique=True)),
                ('miasto', models.CharField(max_length=45)),
                ('kod', models.CharField(max_length=45)),
                ('adres', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ElementSprzedazy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('jednostka', models.CharField(choices=[('usł.', 'usługa'), ('h', 'godzina'), ('kpl.', 'komplet'), ('szt.', 'sztuka'), ('m', 'metr'), ('m2', 'metr kwadratowy'), ('m3', 'metr sześcienny')], default='usł.', max_length=50)),
                ('count', models.IntegerField()),
                ('cena_jednostkowa', models.FloatField()),
                ('vat', models.IntegerField(choices=[(23, '23%'), (8, '8%'), (5, '5%'), (0, '0%')], default=23)),
            ],
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('data_wystawienia', models.DateField()),
                ('miejsce_wystawienia', models.CharField(max_length=45)),
                ('data_wykonania', models.DateField()),
                ('sposob_platnosci', models.CharField(choices=[('przelew na rachunek bankowy', 'przelew na rachunek bankowy'), ('gotówka', 'gotówka'), ('karta płatnicza', 'karta płatnicza')], default='gotówka', max_length=45)),
                ('termin_platnosci', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faktury.company')),
            ],
        ),
        migrations.CreateModel(
            name='Faktura_elementy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_sprzedazy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faktury.elementsprzedazy')),
                ('faktura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faktury.faktura')),
            ],
        ),
        migrations.AddField(
            model_name='faktura',
            name='elementy_sprzedazy',
            field=models.ManyToManyField(through='faktury.Faktura_elementy', to='faktury.ElementSprzedazy'),
        ),
    ]
